version: "3.7"

services:
  app:
    build:
      args:
        user: artim
        uid: 1000
        working_dir: /var/www/app
      context: docker/php
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./:/var/www/app
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: oneteam
      MYSQL_USER: artim
      MYSQL_PASSWORD: artim
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/conf:/etc/nginx/conf.d
    ports:
      - "8000:8000"
      - "3000:3000"
    depends_on:
      - app
